// GPIO

#define OFF_GPIO_PA_BASE 0x00
#define OFF_GPIO_PB_BASE 0x24
#define OFF_GPIO_PC_BASE 0x48

#define OFF_GPIO_PA_CTRL     (OFF_GPIO_PA_BASE + 0x00)
#define OFF_GPIO_PA_MODEL    (OFF_GPIO_PA_BASE + 0x04)
#define OFF_GPIO_PA_MODEH    (OFF_GPIO_PA_BASE + 0x08)
#define OFF_GPIO_PA_DOUT     (OFF_GPIO_PA_BASE + 0x0c)
#define OFF_GPIO_PA_DOUTSET  (OFF_GPIO_PA_BASE + 0x10)
#define OFF_GPIO_PA_DOUTCLR  (OFF_GPIO_PA_BASE + 0x14)
#define OFF_GPIO_PA_DOUTTGL  (OFF_GPIO_PA_BASE + 0x18)
#define OFF_GPIO_PA_DIN      (OFF_GPIO_PA_BASE + 0x1c)
#define OFF_GPIO_PA_PINLOCKN (OFF_GPIO_PA_BASE + 0x20)

#define OFF_GPIO_PB_CTRL     (OFF_GPIO_PB_BASE + 0x00)
#define OFF_GPIO_PB_MODEL    (OFF_GPIO_PB_BASE + 0x04)
#define OFF_GPIO_PB_MODEH    (OFF_GPIO_PB_BASE + 0x08)
#define OFF_GPIO_PB_DOUT     (OFF_GPIO_PB_BASE + 0x0c)
#define OFF_GPIO_PB_DOUTSET  (OFF_GPIO_PB_BASE + 0x10)
#define OFF_GPIO_PB_DOUTCLR  (OFF_GPIO_PB_BASE + 0x14)
#define OFF_GPIO_PB_DOUTTGL  (OFF_GPIO_PB_BASE + 0x18)
#define OFF_GPIO_PB_DIN      (OFF_GPIO_PB_BASE + 0x1c)
#define OFF_GPIO_PB_PINLOCKN (OFF_GPIO_PB_BASE + 0x20)

#define OFF_GPIO_PC_CTRL     (OFF_GPIO_PC_BASE + 0x00)
#define OFF_GPIO_PC_MODEL    (OFF_GPIO_PC_BASE + 0x04)
#define OFF_GPIO_PC_MODEH    (OFF_GPIO_PC_BASE + 0x08)
#define OFF_GPIO_PC_DOUT     (OFF_GPIO_PC_BASE + 0x0c)
#define OFF_GPIO_PC_DOUTSET  (OFF_GPIO_PC_BASE + 0x10)
#define OFF_GPIO_PC_DOUTCLR  (OFF_GPIO_PC_BASE + 0x14)
#define OFF_GPIO_PC_DOUTTGL  (OFF_GPIO_PC_BASE + 0x18)
#define OFF_GPIO_PC_DIN      (OFF_GPIO_PC_BASE + 0x1c)
#define OFF_GPIO_PC_PINLOCKN (OFF_GPIO_PC_BASE + 0x20)

#define OFF_GPIO_EXTIPSELL   (OFF_GPIO_PA_BASE + 0x100)
#define OFF_GPIO_EXTIPSELH   (OFF_GPIO_PA_BASE + 0x104)
#define OFF_GPIO_EXTIRISE    (OFF_GPIO_PA_BASE + 0x108)
#define OFF_GPIO_EXTIFALL    (OFF_GPIO_PA_BASE + 0x10c)
#define OFF_GPIO_IEN         (OFF_GPIO_PA_BASE + 0x110)
#define OFF_GPIO_IFC         (OFF_GPIO_PA_BASE + 0x11c)
#define OFF_GPIO_IF          (OFF_GPIO_PA_BASE + 0x114)

// DAC
#define OFF_DAC0_CTRL        0x000
#define OFF_DAC0_CH0CTRL     0x008
#define OFF_DAC0_CH1CTRL     0x00c
#define OFF_DAC0_IEN         0x010
#define OFF_DAC0_IF          0x014
#define OFF_DAC0_IFS         0x018
#define OFF_DAC0_IFC         0x01c
#define OFF_DAC0_CH0DATA     0x020
#define OFF_DAC0_CH1DATA     0x024
#define OFF_DAC0_COMBDATA    0x028

// Timer
#define OFF_TIMER_CTRL          0x00
#define OFF_TIMER_CMD           0x04
#define OFF_TIMER_IEN           0x0c
#define OFF_TIMER_IFC           0x18
#define OFF_TIMER_TOP           0x1c
#define OFF_TIMER_CNT           0x24
